[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
name = "ebn_client"
crate-type = ["cdylib"]

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
windows =  { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
]}
